language: rust
sudo: true
cache: cargo
deploy:
  provider: releases
  api_key:
    secure: GfZ2FxccNG8GkJArFlFozlP90HloAp7Ko9oumdD6yNkF0oI8fKjtnmrpLllMz5UGPzZtG147eXzXLkSFrpov47Fyor0E6DIwPjJr32gIu8VY+wpucrn/I+VxDMco9tm0QzFL9cn/jx924xoFRc+koRrt+eUBi33JutMWgZOJmeQ1Ri+jBcoof7qoqae0ha6vM24/KPmGHmjNVw5NNC3kXb0VRMYJktzaELDVSVnHL7ndmCv4Xgrh42/PQYgIc/xtcF6bqYWIaQjMffcDGa3rgNhpvxWrPw+Kcv1pcseBw+6r8LJeago97DlpWkp/wFdrcFJv6IjhQS/aQhQqYzMhhNe8eXHTINGUvo5qJv5Ldvn30qPPmFf3FFqGEsDX+BL+9Wp4s2XX3edb3tF+GTEOaCf/OmtMyjGMd+2tBhXPIRFyBi5YMmrupbmbZKcWBRctKvgNHE/zTRYYuT87jtRLfrfxXBx50qclkxO0Z0vI9v5ztCYOR0FvsI4dMl+CV15rhjzFtT3YnVj6+y3ucy+9yR02B++DlOutSffh15IbmEgrSr5ZE/DqNeOszOQvku+oXO9z4lIEYWwzVJzg48++UWxYGJ0ohPxcLNq3yM4hz43KQ5dKhfni9pYWnGqUwxWtuHTyNQzb42vIdISnJH5UBP2xF6r0+LMPHY8/5huqAh0=
  file: target/release/eltrafico
  skip_cleanup: true
  on:
    repo: sigmaSd/Eltrafico
    branch: travis_test
script:
- sudo apt-get install libgtk-3-dev
- cargo b --release
notifications:
  email:
    on_success: never
