[package]
name = "eltrafico"
version = "1.1.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "NetLimiter-like traffic shaping for Linux"
repository = "https://github.com/sigmaSd/Eltrafico/"
license = "GPL3"

[dependencies]
gtk = "0.8.0"
glib = "0.9.0"
gio = "0.8.0"
