[package]
name = "eltrafico"
version = "1.0.1"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.8.0"
glib = "0.9.0"
gio = "0.8.0"
